const facile = [
	"chat",
	"chien",
	"pain",
	"lait",
	"eau",
	"sel",
	"sucre",
	"table",
	"chaise",
	"porte",
	"mur",
	"sol",
	"main",
	"pied",
	"tete",
	"nez",
	"yeux",
	"bras",
	"jambe",
	"dos",
	"ami",
	"amie",
	"pere",
	"mere",
	"frere",
	"soeur",
	"oncle",
	"tante",
	"jour",
	"nuit",
	"matin",
	"soir",
	"hier",
	"demain",
	"ici",
	"la",
	"oui",
	"non",
	"bien",
	"mal",
	"vite",
	"lent",
	"haut",
	"bas",
	"gros",
	"petit",
	"beau",
	"laid",
	"vrai",
	"faux",
	"bon",
	"mauvais",
	"chaud",
	"froid",
	"plein",
	"vide",
	"dur",
	"mou",
	"clair",
	"sombre",
	"neuf",
	"vieux",
	"je",
	"tu",
	"il",
	"elle",
	"nous",
	"vous",
	"eux",
	"elles",
	"mon",
	"ton",
	"son",
	"notre",
	"votre",
	"leur",
	"ce",
	"cet",
	"cette",
	"ces",
	"un",
	"une",
	"des",
	"le",
	"la",
	"les",
	"du",
	"au",
	"aux",
	"sur",
	"sous",
	"dans",
	"avec",
	"sans",
	"vers",
	"pour",
	"contre",
	"chez",
	"entre",
	"avant",
	"apres",
	"pendant",
	"toujours",
	"souvent",
	"parfois",
	"jamais",
	"encore",
	"deja",
	"trop",
	"peu",
	"beaucoup",
	"tout",
	"rien",
	"quelque",
	"ainsi",
	"alors",
	"donc",
	"mais",
	"ou",
	"et",
	"car",
	"si",
	"quand",
	"comme",
	"pourquoi",
	"comment",
	"combien",
	"oublie",
	"trouve",
	"pense",
	"aime",
	"marche",
	"court",
	"saute",
	"parle",
	"crie",
	"rit",
	"pleure",
	"mange",
	"boit",
	"dort",
	"lit",
	"ecrit",
	"ouvre",
	"ferme",
	"tourne",
	"regarde",
	"ecoute",
	"attend",
	"prend",
	"pose",
	"donne",
	"garde",
	"cherche",
	"montre",
	"pousse",
	"tire",
	"porte",
	"tombe",
	"leve",
	"baisse",
	"monte",
	"descend",
	"arrive",
	"part",
	"reste",
	"vient",
	"voit",
	"sent",
	"touche",
	"essaie",
	"joue",
	"gagne",
	"perd",
	"change",
	"ajoute",
	"retire",
	"coupe",
	"colle",
	"range",
	"lave",
	"seche",
	"plie",
	"ouvre",
	"ferme",
];
const moyen = [
	"maison",
	"voiture",
	"ordinateur",
	"clavier",
	"ecran",
	"telephone",
	"fenetre",
	"cuisine",
	"salon",
	"chambre",
	"bureau",
	"travail",
	"ecole",
	"college",
	"universite",
	"professeur",
	"eleve",
	"etudiant",
	"exercice",
	"question",
	"reponse",
	"solution",
	"probleme",
	"histoire",
	"geographie",
	"science",
	"nature",
	"animal",
	"plante",
	"montagne",
	"riviere",
	"ocean",
	"foret",
	"prairie",
	"desert",
	"nuage",
	"pluie",
	"orage",
	"vent",
	"soleil",
	"etoile",
	"planete",
	"galaxie",
	"univers",
	"energie",
	"force",
	"vitesse",
	"distance",
	"volume",
	"surface",
	"temperature",
	"pression",
	"matiere",
	"atome",
	"molecule",
	"reaction",
	"experience",
	"analyse",
	"mesure",
	"calcul",
	"nombre",
	"valeur",
	"resultat",
	"fonction",
	"variable",
	"tableau",
	"liste",
	"donnee",
	"fichier",
	"dossier",
	"reseau",
	"internet",
	"serveur",
	"logiciel",
	"programme",
	"developpeur",
	"application",
	"navigation",
	"connexion",
	"securite",
	"identifiant",
	"motdepasse",
	"interface",
	"utilisateur",
	"parametre",
	"configuration",
	"installation",
	"miseajour",
	"version",
	"prototype",
	"conception",
	"architecture",
	"structure",
	"organisation",
	"strategie",
	"gestion",
	"projet",
	"planning",
	"objectif",
	"priorite",
	"qualite",
	"performance",
	"amelioration",
	"optimisation",
	"creation",
	"invention",
	"decouverte",
	"innovation",
	"imagination",
	"inspiration",
	"motivation",
	"concentration",
	"attention",
	"memoire",
	"reflexion",
	"decision",
	"evaluation",
	"comparaison",
	"observation",
	"description",
	"explication",
	"interpretation",
	"communication",
	"discussion",
	"conversation",
	"argument",
	"opinion",
	"information",
	"connaissance",
	"apprentissage",
	"formation",
	"education",
	"enseignement",
	"lecture",
	"ecriture",
	"redaction",
	"traduction",
	"prononciation",
	"grammaire",
	"orthographe",
	"vocabulaire",
	"expression",
	"langage",
	"discours",
	"presentation",
	"conference",
	"reunion",
	"collaboration",
	"partenariat",
	"negociation",
	"transaction",
	"commerce",
	"entreprise",
	"industrie",
	"production",
	"distribution",
	"livraison",
	"transport",
	"logistique",
	"itineraire",
	"destination",
	"voyage",
	"tourisme",
	"aventure",
	"exploration",
	"experience",
	"souvenir",
	"emotion",
	"sensation",
	"impression",
	"reaction",
	"adaptation",
	"transformation",
	"evolution",
	"progression",
	"developpement",
	"croissance",
];
const difficile = [
	"administration",
	"organisationnel",
	"responsabilite",
	"professionnel",
	"developpement",
	"implementation",
	"international",
	"communication",
	"interpretation",
	"collaboration",
	"coordination",
	"experimentale",
	"documentation",
	"classification",
	"transformation",
	"optimisation",
	"configuration",
	"synchronisation",
	"visualisation",
	"representation",
	"identification",
	"authentification",
	"autorisation",
	"infrastructure",
	"architecture",
	"algorithmique",
	"programmation",
	"compilation",
	"interoperabilite",
	"compatibilite",
	"virtualisation",
	"containerisation",
	"automatisation",
	"orchestration",
	"distribution",
	"sauvegarde",
	"restauration",
	"supervision",
	"monitoring",
	"performance",
	"scalabilite",
	"resilience",
	"tolerance",
	"redondance",
	"migration",
	"integration",
	"deploiement",
	"production",
	"validation",
	"verification",
	"evaluation",
	"amelioration",
	"innovation",
	"technologique",
	"scientifique",
	"experimentateur",
	"interpretatif",
	"comparatif",
	"demonstration",
	"illustration",
	"argumentation",
	"problematique",
	"hypothese",
	"methodologie",
	"statistique",
	"probabilite",
	"modelisation",
	"simulation",
	"analyseur",
	"predictif",
	"correlation",
	"causalite",
	"observationnel",
	"phenomenologie",
	"neuroscience",
	"biologie",
	"genetique",
	"physiologie",
	"biochimie",
	"metabolisme",
	"photosynthese",
	"biodiversite",
	"ecosysteme",
	"environnemental",
	"climatique",
	"geologique",
	"tectonique",
	"sismologie",
	"astronomie",
	"astrophysique",
	"cosmologie",
	"gravitation",
	"relativite",
	"quantification",
	"electromagnetisme",
	"thermodynamique",
	"cristallisation",
	"polymerisation",
	"nanotechnologie",
	"cybersecurite",
	"cryptographie",
	"authentificateur",
	"certification",
	"normalisation",
	"standardisation",
	"industrialisation",
	"commercialisation",
	"internationalisation",
	"regionalisation",
	"urbanisation",
	"modernisation",
	"numerisation",
	"digitalisation",
	"interconnexion",
	"interdependance",
	"globalisation",
	"diversification",
	"specialisation",
	"professionnalisation",
	"responsabilisation",
	"conscientisation",
	"sensibilisation",
	"contextualisation",
	"conceptualisation",
	"operationalisation",
	"institutionnalisation",
	"legislation",
	"reglementation",
	"administratif",
	"bureaucratique",
	"juridictionnel",
	"constitutionnel",
	"parlementaire",
	"gouvernemental",
	"diplomatique",
	"geopolitique",
	"democratique",
	"participatif",
	"consultatif",
	"deliberation",
	"negociation",
	"arbitrage",
	"conciliation",
	"mediation",
	"resolution",
	"interpretation",
	"argumentatif",
	"persuasion",
	"rhetorique",
	"philosophique",
	"epistemologie",
	"metaphysique",
	"ontologie",
	"ethique",
	"dialectique",
	"hermeneutique",
	"existentialisme",
	"structuralisme",
	"postmodernisme",
	"interdisciplinarite",
	"transdisciplinarite",
	"multidimensionnel",
];
const dialog = document.querySelector("dialog");
const easy = document.querySelector("#Easy");
const medium = document.querySelector("#Medium");
const hard = document.querySelector("#Hard");
let tableau = [];
const placeholder = document.querySelector("#placeholder");
let isClicked = false;
const start = document.querySelector("#start");
const time = document.querySelector("#time");
const wpm = document.querySelector("#wpm");
const accuracy = document.querySelector("#accuracy");
const restart = document.querySelector("#restart");
const typing = document.querySelector("#typing");
time.textContent = 60;

start.addEventListener("click", () => {
	dialog.close();
	time.style.color = "#f4dc73";
	accuracy.style.color = "#d64d5b";
	const newBtn = document.createElement("button");
	newBtn.classList.add("button-gray");
	newBtn.classList.add("restart2");
	restart.appendChild(newBtn);
	newBtn.textContent = "Restart Test";
	typing.style.borderBottom = "1px solid #3a3a3a";
	const restart2 = document.querySelector(".restart2");

	const timer = setInterval(() => {
		time.textContent = parseInt(time.textContent) - 1;

		if (parseInt(time.textContent) === 0) {
			clearInterval(timer);
			window.location.href = "result.html";
		}
	}, 1000);
	restart2.addEventListener("click", () => {
		window.location.href = "index.html";
	});
});

easy.addEventListener("click", () => {
	easy.style.color = "#4ca6ff";
	easy.style.border = "1px solid #4ca6ff";
	medium.style.color = "#FFFFFF";
	medium.style.border = "1px solid #717178";
	hard.style.color = "#FFFFFF";
	hard.style.border = "1px solid #717178";

	if (isClicked == false)
		for (let i = 0; i < 80; i++) {
			const random = Math.round(Math.random() * facile.length);
			tableau.push(facile[random]);
			const newSpan = document.createElement("span");
			newSpan.textContent = facile[random] + " ";
			placeholder.appendChild(newSpan);
			// if (placeholder.value == ) {
			// 	console.log("lol");
			// }
		}
	isClicked = true;
});
medium.addEventListener("click", () => {
	medium.style.color = "#4ca6ff";
	medium.style.border = "1px solid #4ca6ff";
	easy.style.color = "#FFFFFF";
	easy.style.border = "1px solid #717178";
	hard.style.color = "#FFFFFF";
	hard.style.border = "1px solid #717178";
	if (isClicked == false) {
		for (let i = 0; i < 80; i++) {
			const random = Math.round(Math.random() * moyen.length);
			tableau.push(moyen[random]);

			const newSpan = document.createElement("span");
			newSpan.textContent = moyen[random] + " ";
			placeholder.appendChild(newSpan);
		}
	}
	isClicked = true;
});
hard.addEventListener("click", () => {
	hard.style.color = "#4ca6ff";
	hard.style.border = "1px solid #4ca6ff";
	medium.style.color = "#FFFFFF";
	medium.style.border = "1px solid #717178";
	easy.style.color = "#FFFFFF";
	easy.style.border = "1px solid #717178";
	difficulty = "hard";
	if (isClicked == false) {
		for (let i = 0; i < 80; i++) {
			const random = Math.round(Math.random() * difficile.length);
			tableau.push(difficile[random]);

			const newSpan = document.createElement("span");
			newSpan.textContent = difficile[random] + " ";
			placeholder.appendChild(newSpan);
		}
	}
});
